Rse 1296 award custom field ui
compucorp/uk.co.compucorp.civiawards pull request #130
Opened 2020-09-14 07:19 UTC by deb1990

## Overview
_A brief description of the pull request. Try to keep it non-technical._

## Before
_The current status. Please provide screenshots or gifs ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)) where appropriate._

## After
_What has been changed. Please provide screenshots or gifs ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)) where appropriate._

## Technical Details
_If the PR introduces noteworthy technical changes, please describe them here. Provide code snippets if necessary_

### Core overrides
_If the PR overrides/patches a core file, then please explain here, for each file:_

1. _Which file it is_
2. _The reason why it was overridden/patched_
3. _What the override/patch consists of_

## Comments
_Anything else you would like the reviewer to note_

2020-09-14 22:14 UTC, reneolivo requested changes

2020-09-14 22:14 UTC, reneolivo commented on ang/civiawards/award-creation/directives/award-custom-field-sets.directive.js
> +})(angular, CRM.$, CRM._, CRM.url);
remove `CRM._` and `CRM.url`

2020-09-14 22:14 UTC, reneolivo commented on ang/test/civiawards/award-creation/directives/award-custom-field-sets.directive.spec.js
> +        spyOn($.fn, 'unblock').and.callThrough();
when overriding functions like this we need to restore them in an `afterEach` otherwise we risk breaking other tests.

2020-09-15 06:28 UTC, deb1990 commented on ang/civiawards/award-creation/directives/award-custom-field-sets.directive.js
> +(function (angular, $, _, getCrmUrl) {
`_` is actually used, so removed the other.

2020-09-15 11:27 UTC, reneolivo approved these changes

2020-09-30 11:36 UTC, reneolivo submitted a review, later dismissed

2020-10-01 12:26 UTC, reneolivo approved these changes

2020-10-09 06:02 UTC, merged