ACU-493: Display payments
compucorp/uk.co.compucorp.civiawards pull request #184
Opened 2021-02-08 20:56 UTC by reneolivo

## Overview
This PR displays the list of payments for an application.

## Before

## After
<img width="1691" alt="Screen Shot 2021-02-08 at 4 41 47 PM" src="https://user-images.githubusercontent.com/1642119/107279405-61b11580-6a2d-11eb-98d8-59f91fabe43e.png">

* Note: placeholders will be added with the filters.

## Technical Details

* A new `gulp test:watch` task was added. This gulp task makes working with tests easier, specially when doing TDD.
* A new `payments-table` directive was created. This directive loads the payment activities and displays them.
* The list of payments types were added as an Angular constant so we could translate payments values such as `'1'` or `'2'` into `'Stipend/Salary'` or `'Expenses'`.
* Some mock values were added for payments, types, and custom fields. The `karma.conf.js` file was updated so it includes these mock values first regardless of the module.

2021-02-09 06:03 UTC, deb1990 requested changes

2021-02-09 06:03 UTC, deb1990 commented on ang/civiawards-payments-tab/directives/payments-table.directive.html
> +<div class="civiawards__reviews-tab__table-container panel panel-default">
If we are using `civiawards__reviews-tab__table-container`, we should give it a more generic name.

2021-02-09 06:03 UTC, deb1990 commented on ang/civiawards-payments-tab/directives/payments-table.directive.js
> +
Please remove Extra line.

2021-02-09 06:57 UTC, deb1990 commented
@reneolivo Can we also add a Empty State, just like Review Tab?

2021-02-11 07:18 UTC, swastikpareek commented
@reneolivo : 
* Should we make the PR title a bit more descriptive. `ACU-493: Display payments info on the payments tab`?
* Is the PR following the [PR writing guidelines](https://compucorp.atlassian.net/wiki/spaces/SD/pages/1520304185/Pull+Requests+guidelines)?

2021-02-15 12:10 UTC, deb1990 approved these changes

2021-02-15 23:56 UTC, merged