ACU-545: Payments form fix for Activity Feed
compucorp/uk.co.compucorp.civiawards pull request #214
Opened 2021-03-12 10:24 UTC by deb1990

## Overview
_A brief description of the pull request. Try to keep it non-technical._

## Before
_The current status. Please provide screenshots or gifs ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)) where appropriate._

## After
_What has been changed. Please provide screenshots or gifs ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)) where appropriate._

## Technical Details
_If the PR introduces noteworthy technical changes, please describe them here. Provide code snippets if necessary_

### Core overrides
_If the PR overrides/patches a core file, then please explain here, for each file:_

1. _Which file it is_
2. _The reason why it was overridden/patched_
3. _What the override/patch consists of_

## Comments
_Anything else you would like the reviewer to note_

2021-03-12 12:14 UTC, reneolivo requested changes

2021-03-12 12:14 UTC, reneolivo commented on ang/civiawards-payments-tab/services/payments-activity-form.service.js
> +})(CRM._, angular);
please remove all references to the review service :)

2021-03-12 12:21 UTC, reneolivo approved these changes

2021-03-18 14:06 UTC, tunbola requested changes

2021-03-18 14:06 UTC, tunbola commented on api/v3/FinanceManagement.php
> +}
Can we make the two API parameters required?

2021-03-19 08:38 UTC, tunbola approved these changes

2021-03-24 16:56 UTC, merged